os: linux
dist: focal
services: docker
language: minimal
install: skip
addons:
  apt:
    packages:
    - pass
script: ./travis.sh -b
deploy:
  provider: script
  skip_cleanup: true
  script: ./travis.sh -d
  on:
    repo: SpinalHDL/docker
    branch: master
